export const TOP_INVESTORS = [
  // Tech Stocks
  { name: "Sarah Johnson", specialty: "Tech Stocks", return: 25.5, country: "USA" },
  { name: "Alex Thompson", specialty: "Tech Stocks", return: 23.4, country: "USA" },
  { name: "Linda Chen", specialty: "Tech Stocks", return: 24.2, country: "China" },
  { name: "David Park", specialty: "Tech Stocks", return: 22.8, country: "Japan" },
  { name: "Emma Wilson", specialty: "Tech Stocks", return: 26.1, country: "USA" },
  { name: "James Miller", specialty: "Tech Stocks", return: 24.7, country: "USA" },
  { name: "Sophie Zhang", specialty: "Tech Stocks", return: 25.9, country: "China" },
  { name: "Robert Taylor", specialty: "Tech Stocks", return: 23.8, country: "USA" },
  { name: "Maria Garcia", specialty: "Tech Stocks", return: 24.5, country: "USA" },
  { name: "Thomas Brown", specialty: "Tech Stocks", return: 25.2, country: "USA" },

  // Crypto
  { name: "Michael Chen", specialty: "Crypto", return: 22.8, country: "USA" },
  { name: "Anna Lee", specialty: "Crypto", return: 24.5, country: "USA" },
  { name: "John Smith", specialty: "Crypto", return: 23.7, country: "USA" },
  { name: "Lisa Wang", specialty: "Crypto", return: 25.1, country: "China" },
  { name: "Daniel Kim", specialty: "Crypto", return: 26.3, country: "USA" },
  { name: "Rachel Green", specialty: "Crypto", return: 24.9, country: "USA" },
  { name: "Kevin Liu", specialty: "Crypto", return: 23.2, country: "USA" },
  { name: "Emily Davis", specialty: "Crypto", return: 25.7, country: "USA" },
  { name: "Mark Wilson", specialty: "Crypto", return: 24.1, country: "USA" },
  { name: "Jessica Chen", specialty: "Crypto", return: 25.4, country: "China" },

  // Real Estate
  { name: "Elena Rodriguez", specialty: "Real Estate", return: 19.2, country: "USA" },
  { name: "Carlos Martinez", specialty: "Real Estate", return: 18.7, country: "USA" },
  { name: "Isabella Silva", specialty: "Real Estate", return: 20.1, country: "Brazil" },
  { name: "Miguel Santos", specialty: "Real Estate", return: 19.8, country: "USA" },
  { name: "Ana Perez", specialty: "Real Estate", return: 18.9, country: "Spain" },
  { name: "Roberto Gomez", specialty: "Real Estate", return: 19.5, country: "USA" },
  { name: "Carmen Lopez", specialty: "Real Estate", return: 20.3, country: "USA" },
  { name: "Juan Torres", specialty: "Real Estate", return: 19.1, country: "USA" },
  { name: "Sofia Ruiz", specialty: "Real Estate", return: 18.8, country: "USA" },
  { name: "Diego Herrera", specialty: "Real Estate", return: 19.7, country: "USA" },

  // Dividend Stocks
  { name: "Hans Weber", specialty: "Dividend Stocks", return: 18.5, country: "Germany" },
  { name: "Greta Schmidt", specialty: "Dividend Stocks", return: 17.9, country: "Germany" },
  { name: "Klaus Mueller", specialty: "Dividend Stocks", return: 18.8, country: "Germany" },
  { name: "Heidi Wagner", specialty: "Dividend Stocks", return: 19.2, country: "Germany" },
  { name: "Franz Fischer", specialty: "Dividend Stocks", return: 18.1, country: "Germany" },
  { name: "Ingrid Bauer", specialty: "Dividend Stocks", return: 18.7, country: "Germany" },
  { name: "Otto Schulz", specialty: "Dividend Stocks", return: 19.4, country: "Germany" },
  { name: "Ursula Koch", specialty: "Dividend Stocks", return: 18.3, country: "Germany" },
  { name: "Werner Hoffman", specialty: "Dividend Stocks", return: 17.8, country: "Germany" },
  { name: "Sabine Meyer", specialty: "Dividend Stocks", return: 18.9, country: "Germany" },

  // Forex Trading
  { name: "Yuki Tanaka", specialty: "Forex Trading", return: 21.3, country: "Japan" },
  { name: "Hiroshi Sato", specialty: "Forex Trading", return: 22.1, country: "Japan" },
  { name: "Akiko Yamamoto", specialty: "Forex Trading", return: 20.8, country: "Japan" },
  { name: "Kenji Suzuki", specialty: "Forex Trading", return: 21.7, country: "Japan" },
  { name: "Sakura Ito", specialty: "Forex Trading", return: 22.4, country: "Japan" },
  { name: "Takeshi Nakamura", specialty: "Forex Trading", return: 21.5, country: "Japan" },
  { name: "Yumi Kobayashi", specialty: "Forex Trading", return: 20.9, country: "Japan" },
  { name: "Ryu Watanabe", specialty: "Forex Trading", return: 21.8, country: "Japan" },
  { name: "Mei Takahashi", specialty: "Forex Trading", return: 22.2, country: "Japan" },
  { name: "Kaito Saito", specialty: "Forex Trading", return: 21.1, country: "Japan" },

  // Commodities
  { name: "Maria Silva", specialty: "Commodities", return: 24.1, country: "Brazil" },
  { name: "Pedro Santos", specialty: "Commodities", return: 23.7, country: "Brazil" },
  { name: "Lucia Oliveira", specialty: "Commodities", return: 24.5, country: "Brazil" },
  { name: "Andre Costa", specialty: "Commodities", return: 23.9, country: "Brazil" },
  { name: "Beatriz Lima", specialty: "Commodities", return: 24.8, country: "Brazil" },
  { name: "Rafael Pereira", specialty: "Commodities", return: 23.4, country: "Brazil" },
  { name: "Carolina Souza", specialty: "Commodities", return: 24.3, country: "Brazil" },
  { name: "Fernando Almeida", specialty: "Commodities", return: 23.8, country: "Brazil" },
  { name: "Mariana Santos", specialty: "Commodities", return: 24.6, country: "Brazil" },
  { name: "Gabriel Silva", specialty: "Commodities", return: 23.5, country: "Brazil" },

  // ESG Investments
  { name: "Alex Thompson", specialty: "ESG Investments", return: 20.7, country: "USA" },
  { name: "Emma Green", specialty: "ESG Investments", return: 21.2, country: "USA" },
  { name: "Oliver Brown", specialty: "ESG Investments", return: 20.4, country: "USA" },
  { name: "Sophie Clark", specialty: "ESG Investments", return: 21.5, country: "USA" },
  { name: "William White", specialty: "ESG Investments", return: 20.9, country: "USA" },
  { name: "Lucy Taylor", specialty: "ESG Investments", return: 21.8, country: "USA" },
  { name: "Henry Wilson", specialty: "ESG Investments", return: 20.3, country: "USA" },
  { name: "Charlotte Davis", specialty: "ESG Investments", return: 21.1, country: "USA" },
  { name: "George Martin", specialty: "ESG Investments", return: 20.8, country: "USA" },
  { name: "Alice Baker", specialty: "ESG Investments", return: 21.4, country: "USA" },

  // Growth Stocks
  { name: "Li Wei", specialty: "Growth Stocks", return: 23.4, country: "China" },
  { name: "Zhang Min", specialty: "Growth Stocks", return: 24.1, country: "China" },
  { name: "Wang Jing", specialty: "Growth Stocks", return: 23.8, country: "China" },
  { name: "Liu Yang", specialty: "Growth Stocks", return: 24.5, country: "China" },
  { name: "Chen Hui", specialty: "Growth Stocks", return: 23.2, country: "China" },
  { name: "Wu Lei", specialty: "Growth Stocks", return: 24.7, country: "China" },
  { name: "Sun Ling", specialty: "Growth Stocks", return: 23.9, country: "China" },
  { name: "Zhou Wei", specialty: "Growth Stocks", return: 24.3, country: "China" },
  { name: "Yang Ming", specialty: "Growth Stocks", return: 23.5, country: "China" },
  { name: "Zhao Xia", specialty: "Growth Stocks", return: 24.2, country: "China" },

  // Mutual Funds
  { name: "David Anderson", specialty: "Mutual Funds", return: 16.8, country: "USA" },
  { name: "Emma Thompson", specialty: "Mutual Funds", return: 17.2, country: "USA" },
  { name: "Carlos Ruiz", specialty: "Mutual Funds", return: 16.5, country: "USA" },
  { name: "Sophie Laurent", specialty: "Mutual Funds", return: 17.5, country: "USA" },
  { name: "James Wilson", specialty: "Mutual Funds", return: 16.9, country: "USA" },
  { name: "Ana García", specialty: "Mutual Funds", return: 17.8, country: "USA" },
  { name: "Marcus Schmidt", specialty: "Mutual Funds", return: 16.3, country: "Germany" },
  { name: "Linda Chen", specialty: "Mutual Funds", return: 17.1, country: "USA" },
  { name: "Roberto Silva", specialty: "Mutual Funds", return: 16.7, country: "Brazil" },
  { name: "Yuki Sato", specialty: "Mutual Funds", return: 17.4, country: "Japan" },

  // Fixed Income
  { name: "John Miller", specialty: "Fixed Income", return: 7.5, country: "USA" },
  { name: "Isabel Santos", specialty: "Fixed Income", return: 7.8, country: "Brazil" },
  { name: "Heinrich Weber", specialty: "Fixed Income", return: 7.2, country: "Germany" },
  { name: "Marie Dubois", specialty: "Fixed Income", return: 7.9, country: "France" },
  { name: "Richard Brown", specialty: "Fixed Income", return: 7.4, country: "USA" },
  { name: "Laura Martinez", specialty: "Fixed Income", return: 8.1, country: "USA" },
  { name: "Thomas Anderson", specialty: "Fixed Income", return: 7.3, country: "USA" },
  { name: "Sofia Rossi", specialty: "Fixed Income", return: 7.7, country: "Italy" },
  { name: "William Chang", specialty: "Fixed Income", return: 7.6, country: "USA" },
  { name: "Elena Popov", specialty: "Fixed Income", return: 8.0, country: "Russia" },

  // Startups
  { name: "Alex Rivera", specialty: "Startups", return: 35.5, country: "USA" },
  { name: "Sarah Kim", specialty: "Startups", return: 36.2, country: "USA" },
  { name: "Mohammed Al-Said", specialty: "Startups", return: 34.8, country: "UAE" },
  { name: "Rachel Green", specialty: "Startups", return: 36.7, country: "USA" },
  { name: "Lucas Silva", specialty: "Startups", return: 35.1, country: "Brazil" },
  { name: "Nina Patel", specialty: "Startups", return: 36.9, country: "India" },
  { name: "Daniel Lee", specialty: "Startups", return: 34.5, country: "USA" },
  { name: "Maria González", specialty: "Startups", return: 35.8, country: "Mexico" },
  { name: "Oliver Schmidt", specialty: "Startups", return: 35.3, country: "Germany" },
  { name: "Aisha Khan", specialty: "Startups", return: 36.4, country: "Pakistan" }
];
