export const TOP_INVESTORS = [
  // Tech Stocks
  { name: "Sarah Johnson", specialty: "Tech Stocks", return: 25.5 },
  { name: "Alex Thompson", specialty: "Tech Stocks", return: 23.4 },
  { name: "Linda Chen", specialty: "Tech Stocks", return: 24.2 },
  { name: "David Park", specialty: "Tech Stocks", return: 22.8 },
  { name: "Emma Wilson", specialty: "Tech Stocks", return: 26.1 },
  { name: "James Miller", specialty: "Tech Stocks", return: 24.7 },
  { name: "Sophie Zhang", specialty: "Tech Stocks", return: 25.9 },
  { name: "Robert Taylor", specialty: "Tech Stocks", return: 23.8 },
  { name: "Maria Garcia", specialty: "Tech Stocks", return: 24.5 },
  { name: "Thomas Brown", specialty: "Tech Stocks", return: 25.2 },

  // Crypto
  { name: "Michael Chen", specialty: "Crypto", return: 22.8 },
  { name: "Anna Lee", specialty: "Crypto", return: 24.5 },
  { name: "John Smith", specialty: "Crypto", return: 23.7 },
  { name: "Lisa Wang", specialty: "Crypto", return: 25.1 },
  { name: "Daniel Kim", specialty: "Crypto", return: 26.3 },
  { name: "Rachel Green", specialty: "Crypto", return: 24.9 },
  { name: "Kevin Liu", specialty: "Crypto", return: 23.2 },
  { name: "Emily Davis", specialty: "Crypto", return: 25.7 },
  { name: "Mark Wilson", specialty: "Crypto", return: 24.1 },
  { name: "Jessica Chen", specialty: "Crypto", return: 25.4 },

  // Real Estate
  { name: "Elena Rodriguez", specialty: "Real Estate", return: 19.2 },
  { name: "Carlos Martinez", specialty: "Real Estate", return: 18.7 },
  { name: "Isabella Silva", specialty: "Real Estate", return: 20.1 },
  { name: "Miguel Santos", specialty: "Real Estate", return: 19.8 },
  { name: "Ana Perez", specialty: "Real Estate", return: 18.9 },
  { name: "Roberto Gomez", specialty: "Real Estate", return: 19.5 },
  { name: "Carmen Lopez", specialty: "Real Estate", return: 20.3 },
  { name: "Juan Torres", specialty: "Real Estate", return: 19.1 },
  { name: "Sofia Ruiz", specialty: "Real Estate", return: 18.8 },
  { name: "Diego Herrera", specialty: "Real Estate", return: 19.7 },

  // Dividend Stocks
  { name: "Hans Weber", specialty: "Dividend Stocks", return: 18.5 },
  { name: "Greta Schmidt", specialty: "Dividend Stocks", return: 17.9 },
  { name: "Klaus Mueller", specialty: "Dividend Stocks", return: 18.8 },
  { name: "Heidi Wagner", specialty: "Dividend Stocks", return: 19.2 },
  { name: "Franz Fischer", specialty: "Dividend Stocks", return: 18.1 },
  { name: "Ingrid Bauer", specialty: "Dividend Stocks", return: 18.7 },
  { name: "Otto Schulz", specialty: "Dividend Stocks", return: 19.4 },
  { name: "Ursula Koch", specialty: "Dividend Stocks", return: 18.3 },
  { name: "Werner Hoffman", specialty: "Dividend Stocks", return: 17.8 },
  { name: "Sabine Meyer", specialty: "Dividend Stocks", return: 18.9 },

  // Forex Trading
  { name: "Yuki Tanaka", specialty: "Forex Trading", return: 21.3 },
  { name: "Hiroshi Sato", specialty: "Forex Trading", return: 22.1 },
  { name: "Akiko Yamamoto", specialty: "Forex Trading", return: 20.8 },
  { name: "Kenji Suzuki", specialty: "Forex Trading", return: 21.7 },
  { name: "Sakura Ito", specialty: "Forex Trading", return: 22.4 },
  { name: "Takeshi Nakamura", specialty: "Forex Trading", return: 21.5 },
  { name: "Yumi Kobayashi", specialty: "Forex Trading", return: 20.9 },
  { name: "Ryu Watanabe", specialty: "Forex Trading", return: 21.8 },
  { name: "Mei Takahashi", specialty: "Forex Trading", return: 22.2 },
  { name: "Kaito Saito", specialty: "Forex Trading", return: 21.1 },

  // Commodities
  { name: "Maria Silva", specialty: "Commodities", return: 24.1 },
  { name: "Pedro Santos", specialty: "Commodities", return: 23.7 },
  { name: "Lucia Oliveira", specialty: "Commodities", return: 24.5 },
  { name: "Andre Costa", specialty: "Commodities", return: 23.9 },
  { name: "Beatriz Lima", specialty: "Commodities", return: 24.8 },
  { name: "Rafael Pereira", specialty: "Commodities", return: 23.4 },
  { name: "Carolina Souza", specialty: "Commodities", return: 24.3 },
  { name: "Fernando Almeida", specialty: "Commodities", return: 23.8 },
  { name: "Mariana Santos", specialty: "Commodities", return: 24.6 },
  { name: "Gabriel Silva", specialty: "Commodities", return: 23.5 },

  // ESG Investments
  { name: "Alex Thompson", specialty: "ESG Investments", return: 20.7 },
  { name: "Emma Green", specialty: "ESG Investments", return: 21.2 },
  { name: "Oliver Brown", specialty: "ESG Investments", return: 20.4 },
  { name: "Sophie Clark", specialty: "ESG Investments", return: 21.5 },
  { name: "William White", specialty: "ESG Investments", return: 20.9 },
  { name: "Lucy Taylor", specialty: "ESG Investments", return: 21.8 },
  { name: "Henry Wilson", specialty: "ESG Investments", return: 20.3 },
  { name: "Charlotte Davis", specialty: "ESG Investments", return: 21.1 },
  { name: "George Martin", specialty: "ESG Investments", return: 20.8 },
  { name: "Alice Baker", specialty: "ESG Investments", return: 21.4 },

  // Growth Stocks
  { name: "Li Wei", specialty: "Growth Stocks", return: 23.4 },
  { name: "Zhang Min", specialty: "Growth Stocks", return: 24.1 },
  { name: "Wang Jing", specialty: "Growth Stocks", return: 23.8 },
  { name: "Liu Yang", specialty: "Growth Stocks", return: 24.5 },
  { name: "Chen Hui", specialty: "Growth Stocks", return: 23.2 },
  { name: "Wu Lei", specialty: "Growth Stocks", return: 24.7 },
  { name: "Sun Ling", specialty: "Growth Stocks", return: 23.9 },
  { name: "Zhou Wei", specialty: "Growth Stocks", return: 24.3 },
  { name: "Yang Ming", specialty: "Growth Stocks", return: 23.5 },
  { name: "Zhao Xia", specialty: "Growth Stocks", return: 24.2 },

  // Mutual Funds
  { name: "David Anderson", specialty: "Mutual Funds", return: 16.8 },
  { name: "Emma Thompson", specialty: "Mutual Funds", return: 17.2 },
  { name: "Carlos Ruiz", specialty: "Mutual Funds", return: 16.5 },
  { name: "Sophie Laurent", specialty: "Mutual Funds", return: 17.5 },
  { name: "James Wilson", specialty: "Mutual Funds", return: 16.9 },
  { name: "Ana García", specialty: "Mutual Funds", return: 17.8 },
  { name: "Marcus Schmidt", specialty: "Mutual Funds", return: 16.3 },
  { name: "Linda Chen", specialty: "Mutual Funds", return: 17.1 },
  { name: "Roberto Silva", specialty: "Mutual Funds", return: 16.7 },
  { name: "Yuki Sato", specialty: "Mutual Funds", return: 17.4 },

  // Fixed Income
  { name: "John Miller", specialty: "Fixed Income", return: 7.5 },
  { name: "Isabel Santos", specialty: "Fixed Income", return: 7.8 },
  { name: "Heinrich Weber", specialty: "Fixed Income", return: 7.2 },
  { name: "Marie Dubois", specialty: "Fixed Income", return: 7.9 },
  { name: "Richard Brown", specialty: "Fixed Income", return: 7.4 },
  { name: "Laura Martinez", specialty: "Fixed Income", return: 8.1 },
  { name: "Thomas Anderson", specialty: "Fixed Income", return: 7.3 },
  { name: "Sofia Rossi", specialty: "Fixed Income", return: 7.7 },
  { name: "William Chang", specialty: "Fixed Income", return: 7.6 },
  { name: "Elena Popov", specialty: "Fixed Income", return: 8.0 },

  // Startups
  { name: "Alex Rivera", specialty: "Startups", return: 35.5 },
  { name: "Sarah Kim", specialty: "Startups", return: 36.2 },
  { name: "Mohammed Al-Said", specialty: "Startups", return: 34.8 },
  { name: "Rachel Green", specialty: "Startups", return: 36.7 },
  { name: "Lucas Silva", specialty: "Startups", return: 35.1 },
  { name: "Nina Patel", specialty: "Startups", return: 36.9 },
  { name: "Daniel Lee", specialty: "Startups", return: 34.5 },
  { name: "Maria González", specialty: "Startups", return: 35.8 },
  { name: "Oliver Schmidt", specialty: "Startups", return: 35.3 },
  { name: "Aisha Khan", specialty: "Startups", return: 36.4 }
];
