// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbehlwivdhlsmudiijxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZWhsd2l2ZGhsc211ZGlpanhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDMzNjIsImV4cCI6MjA1OTg3OTM2Mn0.RC8hAReUz_afUiNWQE730gQNwDfFortVDPF180l-K-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);